[package]
name = "gf2-linalg"
version = "0.1.0"
edition = "2024"

[features]
default = ["rand"]

[dependencies.rand]
version = "0.9"
optional = true
default-features = false

[dev-dependencies.rand]
version = "0.9"
default-features = true
